
services:
  backend:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: szopapka-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/szopapka
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    networks:
      - app-network

  postgres:
    image: postgres:16-alpine
    container_name: db-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: szopapka
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:80"
    networks:
      - app-network
volumes:
  postgres_data:

networks:
  app-network: