name: Build and Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Save Firebase JSON
        run: |
          echo "${{ secrets.FIREBASE_JSON }}" > firebase.json

      - name: Upload Firebase JSON to Azure
        uses: azure/cli@v1
        with:
          inlineScript: |
            az webapp deploy --resource-group szopapka-rg --name szopapka-backend --src-path firebase.json --target-path /home/site/wwwroot/firebase.json --type static

      - name: Build backend
        run: mvn clean package -DskipTests

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'szopapka-backend'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
