name: Deploy Backend to Azure Container Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Logowanie do Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Logowanie do ACR
        run: |
          az acr login --name szopapka

      - name: Budowanie i push obrazu Dockera
        run: |
          docker build -t szopapka.azurecr.io/szopapka-backend:latest .
          docker push szopapka.azurecr.io/szopapka-backend:latest

      - name: Deploy do ACA
        run: |
          az containerapp update \
            --name szopapka-backend \
            --resource-group szopapka \
            --image szopapka.azurecr.io/szopapka-backend:latest
