name: Deploy Backend to Azure Container Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Logowanie do Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Logowanie do ACR
        run: |
          az acr login --name szopapka-acr

      - name: Budowanie i push obrazu Dockera
        run: |
          docker build -t szopapka-acr.azurecr.io/backend:latest .
          docker push szopapka-acr.azurecr.io/backend:latest

      - name: Deploy do ACA
        run: |
          az containerapp update \
            --name backend \
            --resource-group szopapka-rg \
            --image szopapka-acr.azurecr.io/backend:latest
