name: Load Test with Auth

on:
  workflow_dispatch:

jobs:
  load-test:
    runs-on: ubuntu-latest
    env:
      FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      FIREBASE_TEST_EMAIL: ${{ secrets.FIREBASE_TEST_EMAIL }}
      FIREBASE_TEST_PASSWORD: ${{ secrets.FIREBASE_TEST_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - name: Run k6 test
        uses: grafana/k6-action@v0.3.0
        with:
          filename: load-test.js
