name: Azure Load Testing

on:
  workflow_dispatch:

jobs:
  load-test:
    runs-on: ubuntu-latest
    env:
      FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      FIREBASE_TEST_EMAIL: ${{ secrets.FIREBASE_TEST_EMAIL }}
      FIREBASE_TEST_PASSWORD: ${{ secrets.FIREBASE_TEST_PASSWORD }}
      
    steps:
      - uses: actions/checkout@v3
      
      - name: Run Azure Load Test
        uses: azure/load-testing@v1
        with:
          loadTestConfigFile: 'load-test-config.yaml'
          resourceGroup: 'szopapka-rg'  # Twoja grupa zasobów
          loadTestResource: 'szopapka-loadtest'    # Nazwa usługi Azure Load Testing
          token: ${{ secrets.AZURE_CREDENTIALS }} # Service Principal (JSON)
